environment: "dev"
one_step_models_dir: '/home/velka/projs/pharma/dose_predictions_backend/saved_models/one_step_models'
lstm_models_dir: '/home/velka/projs/pharma/dose_predictions_backend/saved_models/lstm_models'